version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
  frontend:
    build: 
      context: ./frontend
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - backend
  yarn-backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    entrypoint: "yarn"
  yarn-frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    entrypoint: "yarn"
  prisma_studio:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    command: yarn run prisma studio
    ports:
      - 5555:5555
volumes:
  backend:
  frontend:
  yarn-backend:
  yarn-frontend:
  pgdata: